/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.84
 * Generated at: 2025-12-25 10:56:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.whoami.model.*;
import java.util.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.whoami.model");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Dashboard - WhoAmI</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");
 
        if (session.getAttribute("userId") == null) {
            response.sendRedirect("login");
            return;
        }
        String userName = (String) session.getAttribute("userName");
        MindLog todayLog = (MindLog) request.getAttribute("todayLog");
        StudySession todaySession = (StudySession) request.getAttribute("todaySession");
        Reflection todayReflection = (Reflection) request.getAttribute("todayReflection");
        List<Streak> streaks = (List<Streak>) request.getAttribute("streaks");
        Boolean welcomeMessage = (Boolean) request.getAttribute("welcomeMessage");
    
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "WEB-INF/navbar.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("activePage", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("dashboard", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("activeSection", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("userName", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf( userName ), request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <main class=\"main-content\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            ");
 if (welcomeMessage != null && welcomeMessage) { 
      out.write("\r\n");
      out.write("                <div class=\"welcome-banner fade-in\">\r\n");
      out.write("                    <h2>Welcome to WhoAmI, ");
      out.print( userName );
      out.write("!</h2>\r\n");
      out.write("                    <p>Let's start by checking in with your mind. Understanding yourself is the first step to growth.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"page-header\">\r\n");
      out.write("                <h1 class=\"page-title\">Your Dashboard</h1>\r\n");
      out.write("                <p class=\"page-subtitle\">Track your mental state, study progress, and personal growth</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"grid grid-3\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <div class=\"card-header\">\r\n");
      out.write("                        <h3 class=\"card-title\">Today's Check-In</h3>\r\n");
      out.write("                        <p class=\"card-subtitle\">Mental state assessment</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");
 if (todayLog != null) { 
      out.write("\r\n");
      out.write("                        <div class=\"stat-card\">\r\n");
      out.write("                            <div class=\"stat-value\" style=\"font-size: 32px;\">");
      out.print( todayLog.getMindState() );
      out.write("</div>\r\n");
      out.write("                            <div class=\"stat-label\">Score: ");
      out.print( String.format("%.1f", todayLog.getMindScore()) );
      out.write("/10</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <a href=\"mind-checkin\" class=\"btn btn-secondary\" style=\"width: 100%; margin-top: 16px;\">Update Check-In</a>\r\n");
      out.write("                    ");
 } else { 
      out.write("\r\n");
      out.write("                        <div class=\"empty-state\" style=\"padding: 32px 16px;\">\r\n");
      out.write("                            <div class=\"empty-state-icon\">MIND</div>\r\n");
      out.write("                            <p>No check-in yet today</p>\r\n");
      out.write("                            <a href=\"mind-checkin\" class=\"btn btn-primary\" style=\"margin-top: 16px;\">Start Check-In</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <div class=\"card-header\">\r\n");
      out.write("                        <h3 class=\"card-title\">Study Recommendation</h3>\r\n");
      out.write("                        <p class=\"card-subtitle\">Based on your mind state</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");
 if (todaySession != null) { 
      out.write("\r\n");
      out.write("                        <div style=\"padding: 16px 0;\">\r\n");
      out.write("                            <p style=\"color: var(--text-secondary); font-size: 14px; margin-bottom: 8px;\">Activity</p>\r\n");
      out.write("                            <p style=\"font-weight: 600; margin-bottom: 16px;\">");
      out.print( todaySession.getSuggestedActivity() );
      out.write("</p>\r\n");
      out.write("                            <p style=\"color: var(--text-secondary); font-size: 14px; margin-bottom: 8px;\">Intensity</p>\r\n");
      out.write("                            <p style=\"font-weight: 600; color: var(--primary);\">");
      out.print( todaySession.getSuggestedIntensity() );
      out.write("</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <a href=\"study-zone\" class=\"btn btn-primary\" style=\"width: 100%; margin-top: 16px;\">View Details</a>\r\n");
      out.write("                    ");
 } else { 
      out.write("\r\n");
      out.write("                        <div class=\"empty-state\" style=\"padding: 32px 16px;\">\r\n");
      out.write("                            <div class=\"empty-state-icon\">STUDY</div>\r\n");
      out.write("                            <p>Complete check-in first</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <div class=\"card-header\">\r\n");
      out.write("                        <h3 class=\"card-title\">Daily Reflection</h3>\r\n");
      out.write("                        <p class=\"card-subtitle\">Journal your thoughts</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");
 if (todayReflection != null) { 
      out.write("\r\n");
      out.write("                        <div class=\"stat-card\">\r\n");
      out.write("                            <div style=\"font-size: 48px; margin-bottom: 16px; color: var(--success); font-weight: bold;\">â</div>\r\n");
      out.write("                            <div class=\"stat-label\">Completed</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <a href=\"reflection\" class=\"btn btn-secondary\" style=\"width: 100%; margin-top: 16px;\">View Reflection</a>\r\n");
      out.write("                    ");
 } else { 
      out.write("\r\n");
      out.write("                        <div class=\"empty-state\" style=\"padding: 32px 16px;\">\r\n");
      out.write("                            <div class=\"empty-state-icon\">NOTES</div>\r\n");
      out.write("                            <p>Not reflected yet</p>\r\n");
      out.write("                            <a href=\"reflection\" class=\"btn btn-primary\" style=\"margin-top: 16px;\">Reflect Now</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"card\" style=\"margin-top: 24px;\">\r\n");
      out.write("                <div class=\"card-header\">\r\n");
      out.write("                    <h3 class=\"card-title\">Your Streaks</h3>\r\n");
      out.write("                    <p class=\"card-subtitle\">Keep the momentum going</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                ");
 if (streaks != null && !streaks.isEmpty()) { 
      out.write("\r\n");
      out.write("                    ");
 for (Streak streak : streaks) { 
      out.write("\r\n");
      out.write("                        <div class=\"streak-display\">\r\n");
      out.write("                            <div class=\"streak-info\">\r\n");
      out.write("                                <div class=\"streak-icon\">");
      out.print( streak.getStreakType().equals("mind_checkin") ? "M" : "S" );
      out.write("</div>\r\n");
      out.write("                                <div class=\"streak-details\">\r\n");
      out.write("                                    <h3>");
      out.print( streak.getStreakType().equals("mind_checkin") ? "Mind Check-In Streak" : "Study Follow-Through Streak" );
      out.write("</h3>\r\n");
      out.write("                                    <p>Keep it going every day</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"streak-count\">\r\n");
      out.write("                                <div class=\"streak-current\">");
      out.print( streak.getCurrentCount() );
      out.write("</div>\r\n");
      out.write("                                <div class=\"streak-best\">Best: ");
      out.print( streak.getBestCount() );
      out.write(" days</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("                    <div class=\"empty-state\">\r\n");
      out.write("                        <p>Start checking in daily to build streaks</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </main>\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"js/theme.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
