/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.84
 * Generated at: 2025-12-25 11:11:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.whoami.model.*;
import java.util.*;
import java.time.format.DateTimeFormatter;

public final class growth_002dtimeline_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.whoami.model");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.time.format.DateTimeFormatter");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Personal Growth Timeline - WhoAmI</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");
 
        if (session.getAttribute("userId") == null) {
            response.sendRedirect("login");
            return;
        }
        String userName = (String) session.getAttribute("userName");
        List<GrowthMetric> metrics = (List<GrowthMetric>) request.getAttribute("metrics");
        String insightMessage = (String) request.getAttribute("insightMessage");
        String trendAnalysis = (String) request.getAttribute("trendAnalysis");
        String avgGrowth = (String) request.getAttribute("avgGrowth");
        String currentView = (String) request.getAttribute("currentView");
        String todayDate = (String) request.getAttribute("todayDate");
        
        DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("MMM dd");
        DateTimeFormatter fullDateFormatter = DateTimeFormatter.ofPattern("MMM dd, yyyy");
    
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "WEB-INF/navbar.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("activePage", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("growth-timeline", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("activeSection", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("growth", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("userName", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf( userName ), request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\" style=\"padding-top: 24px;\">\r\n");
      out.write("        <div class=\"page-header\" style=\"margin-bottom: 32px;\">\r\n");
      out.write("            <div>\r\n");
      out.write("                <h1 style=\"margin: 0 0 8px 0; font-size: 32px;\">Personal Growth Timeline</h1>\r\n");
      out.write("                <p style=\"margin: 0; color: var(--text-secondary); font-size: 16px;\">Track your journey toward consistent improvement</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"view-tabs\" style=\"margin-bottom: 24px;\">\r\n");
      out.write("            <a href=\"growth-timeline?view=week\" class=\"view-tab ");
      out.print( "week".equals(currentView) ? "active" : "" );
      out.write("\">7 Days</a>\r\n");
      out.write("            <a href=\"growth-timeline?view=month\" class=\"view-tab ");
      out.print( "month".equals(currentView) ? "active" : "" );
      out.write("\">30 Days</a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"growth-summary-card\">\r\n");
      out.write("            <div class=\"summary-header\">\r\n");
      out.write("                <h2 style=\"margin: 0; font-size: 20px;\">Growth Summary</h2>\r\n");
      out.write("                <span class=\"trend-badge ");
      out.print( trendAnalysis.toLowerCase() );
      out.write('"');
      out.write('>');
      out.print( trendAnalysis );
      out.write("</span>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"summary-stats\">\r\n");
      out.write("                <div class=\"summary-stat\">\r\n");
      out.write("                    <div class=\"stat-label\">Average Growth</div>\r\n");
      out.write("                    <div class=\"stat-value-large\">");
      out.print( avgGrowth );
      out.write("%</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"summary-stat\">\r\n");
      out.write("                    <div class=\"stat-label\">Days Tracked</div>\r\n");
      out.write("                    <div class=\"stat-value-large\">");
      out.print( metrics != null ? metrics.size() : 0 );
      out.write("</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"growth-insight\">\r\n");
      out.write("                <svg class=\"insight-icon\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                    <path d=\"M22 11.08V12a10 10 0 1 1-5.93-9.14\"></path>\r\n");
      out.write("                    <polyline points=\"22 4 12 14.01 9 11.01\"></polyline>\r\n");
      out.write("                </svg>\r\n");
      out.write("                <p style=\"margin: 0;\">");
      out.print( insightMessage );
      out.write("</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"timeline-section\">\r\n");
      out.write("            <h2 style=\"margin: 0 0 24px 0; font-size: 20px;\">Your Progress Timeline</h2>\r\n");
      out.write("            \r\n");
      out.write("            ");
 if (metrics != null && !metrics.isEmpty()) { 
      out.write("\r\n");
      out.write("            <div class=\"timeline\">\r\n");
      out.write("                ");
 for (int i = 0; i < metrics.size(); i++) { 
                    GrowthMetric metric = metrics.get(i);
                    boolean isLast = (i == metrics.size() - 1);
                
      out.write("\r\n");
      out.write("                <div class=\"timeline-item ");
      out.print( isLast ? "timeline-item-latest" : "" );
      out.write("\">\r\n");
      out.write("                    <div class=\"timeline-marker\">\r\n");
      out.write("                        <div class=\"timeline-dot ");
      out.print( metric.getGrowthTrend().toLowerCase() );
      out.write("\"></div>\r\n");
      out.write("                        ");
 if (!isLast) { 
      out.write("\r\n");
      out.write("                        <div class=\"timeline-line\"></div>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"timeline-content\">\r\n");
      out.write("                        <div class=\"timeline-header\">\r\n");
      out.write("                            <span class=\"timeline-date\">");
      out.print( metric.getMetricDate().format(fullDateFormatter) );
      out.write("</span>\r\n");
      out.write("                            <span class=\"growth-score ");
      out.print( metric.getGrowthTrend().toLowerCase() );
      out.write("\">\r\n");
      out.write("                                ");
      out.print( String.format("%.1f", metric.getOverallGrowth()) );
      out.write("%\r\n");
      out.write("                            </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"metric-grid\">\r\n");
      out.write("                            <div class=\"metric-item\">\r\n");
      out.write("                                <div class=\"metric-header\">\r\n");
      out.write("                                    <svg class=\"metric-icon\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                                        <circle cx=\"12\" cy=\"12\" r=\"10\"></circle>\r\n");
      out.write("                                        <line x1=\"12\" y1=\"16\" x2=\"12\" y2=\"12\"></line>\r\n");
      out.write("                                        <line x1=\"12\" y1=\"8\" x2=\"12.01\" y2=\"8\"></line>\r\n");
      out.write("                                    </svg>\r\n");
      out.write("                                    <span class=\"metric-label\">Mind</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"metric-bar\">\r\n");
      out.write("                                    <div class=\"metric-bar-fill\" style=\"width: ");
      out.print( metric.getMindScore() );
      out.write("%;\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <span class=\"metric-value\">");
      out.print( String.format("%.0f", metric.getMindScore()) );
      out.write("%</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"metric-item\">\r\n");
      out.write("                                <div class=\"metric-header\">\r\n");
      out.write("                                    <svg class=\"metric-icon\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                                        <polyline points=\"22 12 18 12 15 21 9 3 6 12 2 12\"></polyline>\r\n");
      out.write("                                    </svg>\r\n");
      out.write("                                    <span class=\"metric-label\">Tasks</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"metric-bar\">\r\n");
      out.write("                                    <div class=\"metric-bar-fill\" style=\"width: ");
      out.print( metric.getTaskEfficiency() );
      out.write("%;\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <span class=\"metric-value\">");
      out.print( String.format("%.0f", metric.getTaskEfficiency()) );
      out.write("%</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"metric-item\">\r\n");
      out.write("                                <div class=\"metric-header\">\r\n");
      out.write("                                    <svg class=\"metric-icon\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                                        <path d=\"M4 19.5A2.5 2.5 0 0 1 6.5 17H20\"></path>\r\n");
      out.write("                                        <path d=\"M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z\"></path>\r\n");
      out.write("                                    </svg>\r\n");
      out.write("                                    <span class=\"metric-label\">Study</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"metric-bar\">\r\n");
      out.write("                                    <div class=\"metric-bar-fill\" style=\"width: ");
      out.print( metric.getStudyConsistency() );
      out.write("%;\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <span class=\"metric-value\">");
      out.print( String.format("%.0f", metric.getStudyConsistency()) );
      out.write("%</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"metric-item\">\r\n");
      out.write("                                <div class=\"metric-header\">\r\n");
      out.write("                                    <svg class=\"metric-icon\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                                        <path d=\"M12 2v20M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6\"></path>\r\n");
      out.write("                                    </svg>\r\n");
      out.write("                                    <span class=\"metric-label\">Balance</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"metric-bar\">\r\n");
      out.write("                                    <div class=\"metric-bar-fill\" style=\"width: ");
      out.print( metric.getLoadBalance() );
      out.write("%;\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <span class=\"metric-value\">");
      out.print( String.format("%.0f", metric.getLoadBalance()) );
      out.write("%</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("            <div class=\"empty-state\">\r\n");
      out.write("                <svg class=\"empty-icon\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                    <path d=\"M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z\"></path>\r\n");
      out.write("                    <polyline points=\"9 22 9 12 15 12 15 22\"></polyline>\r\n");
      out.write("                </svg>\r\n");
      out.write("                <p style=\"margin: 16px 0 0 0; color: var(--text-secondary);\">\r\n");
      out.write("                    Your growth journey begins now. Start tracking your mind, tasks, and study habits to see your progress over time.\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"js/theme.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
