/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.84
 * Generated at: 2025-12-25 11:43:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.whoami.model.*;
import java.util.*;

public final class insights_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.whoami.model");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Insights - WhoAmI</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");
 
        if (session.getAttribute("userId") == null) {
            response.sendRedirect("login");
            return;
        }
        String userName = (String) session.getAttribute("userName");
        Map<String, Object> weeklyInsights = (Map<String, Object>) request.getAttribute("weeklyInsights");
        Map<String, Object> monthlyInsights = (Map<String, Object>) request.getAttribute("monthlyInsights");
        List<MindLog> weekLogs = (List<MindLog>) request.getAttribute("weekLogs");
    
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "WEB-INF/navbar.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("activePage", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("insights", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("activeSection", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("growth", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("userName", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf( userName ), request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <main class=\"main-content\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"page-header\">\r\n");
      out.write("                <h1 class=\"page-title\">Your Insights</h1>\r\n");
      out.write("                <p class=\"page-subtitle\">Understand your patterns and optimize your productivity</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                <div class=\"card-header\">\r\n");
      out.write("                    <h3 class=\"card-title\">Weekly Overview</h3>\r\n");
      out.write("                    <p class=\"card-subtitle\">Last 7 days</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                ");
 if (weeklyInsights.containsKey("message")) { 
      out.write("\r\n");
      out.write("                    <div class=\"empty-state\">\r\n");
      out.write("                        <p>");
      out.print( weeklyInsights.get("message") );
      out.write("</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("                    <div class=\"insight-narrative\">\r\n");
      out.write("                        ");
      out.print( weeklyInsights.get("narrative") );
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"grid grid-4\">\r\n");
      out.write("                        <div class=\"stat-card\">\r\n");
      out.write("                            <div class=\"stat-value\" style=\"font-size: 36px; color: var(--info);\">");
      out.print( weeklyInsights.get("avgFocus") );
      out.write("</div>\r\n");
      out.write("                            <div class=\"stat-label\">Avg Focus</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"stat-card\">\r\n");
      out.write("                            <div class=\"stat-value\" style=\"font-size: 36px; color: var(--success);\">");
      out.print( weeklyInsights.get("avgEnergy") );
      out.write("</div>\r\n");
      out.write("                            <div class=\"stat-label\">Avg Energy</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"stat-card\">\r\n");
      out.write("                            <div class=\"stat-value\" style=\"font-size: 36px; color: var(--warning);\">");
      out.print( weeklyInsights.get("avgStress") );
      out.write("</div>\r\n");
      out.write("                            <div class=\"stat-label\">Avg Stress</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"stat-card\">\r\n");
      out.write("                            <div class=\"stat-value\" style=\"font-size: 36px; color: var(--primary);\">");
      out.print( weeklyInsights.get("totalCheckins") );
      out.write("</div>\r\n");
      out.write("                            <div class=\"stat-label\">Check-ins</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                <div class=\"card-header\">\r\n");
      out.write("                    <h3 class=\"card-title\">Monthly Trends</h3>\r\n");
      out.write("                    <p class=\"card-subtitle\">Last 30 days</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                ");
 if (monthlyInsights.containsKey("message")) { 
      out.write("\r\n");
      out.write("                    <div class=\"empty-state\">\r\n");
      out.write("                        <p>");
      out.print( monthlyInsights.get("message") );
      out.write("</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("                    <div class=\"insight-narrative\">\r\n");
      out.write("                        ");
      out.print( monthlyInsights.get("narrative") );
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div>\r\n");
      out.write("                        <div class=\"metric-row\">\r\n");
      out.write("                            <span class=\"metric-label\">Average Mind Score</span>\r\n");
      out.write("                            <span class=\"metric-value\" style=\"color: var(--primary);\">");
      out.print( monthlyInsights.get("avgScore") );
      out.write("/10</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"metric-row\">\r\n");
      out.write("                            <span class=\"metric-label\">Average Focus Level</span>\r\n");
      out.write("                            <span class=\"metric-value\">");
      out.print( monthlyInsights.get("avgFocus") );
      out.write("/10</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"metric-row\">\r\n");
      out.write("                            <span class=\"metric-label\">Average Energy Level</span>\r\n");
      out.write("                            <span class=\"metric-value\">");
      out.print( monthlyInsights.get("avgEnergy") );
      out.write("/10</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"metric-row\">\r\n");
      out.write("                            <span class=\"metric-label\">Average Stress Level</span>\r\n");
      out.write("                            <span class=\"metric-value\">");
      out.print( monthlyInsights.get("avgStress") );
      out.write("/10</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"metric-row\">\r\n");
      out.write("                            <span class=\"metric-label\">Your Best Day</span>\r\n");
      out.write("                            <span class=\"metric-value\" style=\"color: var(--success);\">");
      out.print( monthlyInsights.get("bestDay") );
      out.write("</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"metric-row\">\r\n");
      out.write("                            <span class=\"metric-label\">Total Check-ins</span>\r\n");
      out.write("                            <span class=\"metric-value\">");
      out.print( monthlyInsights.get("totalCheckins") );
      out.write(" days</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            ");
 if (weekLogs != null && !weekLogs.isEmpty()) { 
      out.write("\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <div class=\"card-header\">\r\n");
      out.write("                        <h3 class=\"card-title\">Recent Check-ins</h3>\r\n");
      out.write("                        <p class=\"card-subtitle\">Your latest mental state logs</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    ");
 for (MindLog log : weekLogs) { 
      out.write("\r\n");
      out.write("                        <div style=\"padding: 16px; border-bottom: 1px solid var(--border-color); display: flex; justify-content: space-between; align-items: center;\">\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <div style=\"font-weight: 600; color: var(--text-primary); margin-bottom: 4px;\">\r\n");
      out.write("                                    ");
      out.print( log.getLogDate() );
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div style=\"font-size: 14px; color: var(--text-secondary);\">\r\n");
      out.write("                                    ");
      out.print( log.getMindState() );
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div style=\"text-align: right;\">\r\n");
      out.write("                                <div style=\"font-size: 24px; font-weight: 700; color: var(--primary);\">\r\n");
      out.write("                                    ");
      out.print( String.format("%.1f", log.getMindScore()) );
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div style=\"font-size: 12px; color: var(--text-tertiary);\">\r\n");
      out.write("                                    /10\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </main>\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"js/theme.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
