/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.84
 * Generated at: 2025-12-25 11:55:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.whoami.model.*;
import java.util.*;
import java.time.format.DateTimeFormatter;

public final class load_002dbalancer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.whoami.model");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.time.format.DateTimeFormatter");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Study Load Balancer - WhoAmI</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");
 
        if (session.getAttribute("userId") == null) {
            response.sendRedirect("login");
            return;
        }
        String userName = (String) session.getAttribute("userName");
        List<StudyLoad> loads = (List<StudyLoad>) request.getAttribute("loads");
        LoadAnalysis analysis = (LoadAnalysis) request.getAttribute("analysis");
        List<LoadAnalysis> weekAnalyses = (List<LoadAnalysis>) request.getAttribute("weekAnalyses");
        String currentView = (String) request.getAttribute("currentView");
        String todayDate = (String) request.getAttribute("todayDate");
        
        DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("MMM dd");
    
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "WEB-INF/navbar.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("activePage", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("load-balancer", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("activeSection", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("tasks", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("userName", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf( userName ), request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <main class=\"main-content\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"load-balancer-container\">\r\n");
      out.write("                <!-- Hero Section -->\r\n");
      out.write("                <div class=\"load-balancer-hero\">\r\n");
      out.write("                    <div class=\"hero-content\">\r\n");
      out.write("                        <div class=\"hero-text\">\r\n");
      out.write("                            <h1 class=\"hero-title\">Study Load Balancer</h1>\r\n");
      out.write("                            <p class=\"hero-subtitle\">Optimize your academic workload with intelligent distribution and insights</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"hero-actions\">\r\n");
      out.write("                            <button onclick=\"openAddLoadModal()\" class=\"btn-primary-large\">\r\n");
      out.write("                                <svg class=\"btn-icon\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                                    <path d=\"M12 5v14M5 12h14\"></path>\r\n");
      out.write("                                </svg>\r\n");
      out.write("                                Add Subject\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"hero-visual\">\r\n");
      out.write("                        <div class=\"load-distribution-chart\">\r\n");
      out.write("                            <div class=\"chart-placeholder\">\r\n");
      out.write("                                <svg viewBox=\"0 0 120 120\" class=\"chart-icon\">\r\n");
      out.write("                                    <circle cx=\"60\" cy=\"60\" r=\"40\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" opacity=\"0.2\"></circle>\r\n");
      out.write("                                    <circle cx=\"60\" cy=\"60\" r=\"25\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"3\" opacity=\"0.4\"></circle>\r\n");
      out.write("                                    <circle cx=\"60\" cy=\"60\" r=\"15\" fill=\"currentColor\" opacity=\"0.6\"></circle>\r\n");
      out.write("                                </svg>\r\n");
      out.write("                                <p class=\"chart-label\">Load Distribution</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- View Tabs -->\r\n");
      out.write("        <div class=\"view-tabs\">\r\n");
      out.write("            <a href=\"load-balancer?view=today\" class=\"view-tab ");
      out.print( "today".equals(currentView) ? "active" : "" );
      out.write("\">\r\n");
      out.write("                <svg class=\"tab-icon\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                    <circle cx=\"12\" cy=\"12\" r=\"10\"></circle>\r\n");
      out.write("                    <polyline points=\"12,6 12,12 16,14\"></polyline>\r\n");
      out.write("                </svg>\r\n");
      out.write("                Today\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"load-balancer?view=week\" class=\"view-tab ");
      out.print( "week".equals(currentView) ? "active" : "" );
      out.write("\">\r\n");
      out.write("                <svg class=\"tab-icon\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                    <rect x=\"3\" y=\"4\" width=\"18\" height=\"18\" rx=\"2\" ry=\"2\"></rect>\r\n");
      out.write("                    <line x1=\"16\" y1=\"2\" x2=\"16\" y2=\"6\"></line>\r\n");
      out.write("                    <line x1=\"8\" y1=\"2\" x2=\"8\" y2=\"6\"></line>\r\n");
      out.write("                    <line x1=\"3\" y1=\"10\" x2=\"21\" y2=\"10\"></line>\r\n");
      out.write("                </svg>\r\n");
      out.write("                This Week\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        ");
 if ("today".equals(currentView) && analysis != null) { 
      out.write("\r\n");
      out.write("        <!-- Load Analysis Card -->\r\n");
      out.write("        <div class=\"analysis-card\">\r\n");
      out.write("            <div class=\"analysis-card-header\">\r\n");
      out.write("                <div class=\"analysis-title-section\">\r\n");
      out.write("                    <h2 class=\"analysis-title\">");
      out.print( todayDate );
      out.write("</h2>\r\n");
      out.write("                    <div class=\"analysis-status\">\r\n");
      out.write("                        <div class=\"status-indicator ");
      out.print( analysis.getLoadCategory().toLowerCase() );
      out.write("\"></div>\r\n");
      out.write("                        <span class=\"status-text\">");
      out.print( analysis.getLoadCategory() );
      out.write("</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"analysis-metrics\">\r\n");
      out.write("                    <div class=\"metric-item\">\r\n");
      out.write("                        <div class=\"metric-value\">");
      out.print( analysis.getTotalEntries() );
      out.write("</div>\r\n");
      out.write("                        <div class=\"metric-label\">Subjects</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"metric-item\">\r\n");
      out.write("                        <div class=\"metric-value\">");
      out.print( analysis.getLoadScore() );
      out.write("</div>\r\n");
      out.write("                        <div class=\"metric-label\">Load Score</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"analysis-progress-section\">\r\n");
      out.write("                <div class=\"progress-container\">\r\n");
      out.write("                    <div class=\"progress-bar\">\r\n");
      out.write("                        <div class=\"progress-fill ");
      out.print( analysis.getLoadCategory().toLowerCase() );
      out.write("\"\r\n");
      out.write("                             style=\"width: ");
      out.print( Math.min(analysis.getLoadScore(), 100) );
      out.write("%;\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"progress-labels\">\r\n");
      out.write("                        <span>Light</span>\r\n");
      out.write("                        <span>Balanced</span>\r\n");
      out.write("                        <span>Heavy</span>\r\n");
      out.write("                        <span>Overloaded</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"analysis-insight-section\">\r\n");
      out.write("                <div class=\"insight-content\">\r\n");
      out.write("                    <svg class=\"insight-icon\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                        <circle cx=\"12\" cy=\"12\" r=\"10\"></circle>\r\n");
      out.write("                        <line x1=\"12\" y1=\"16\" x2=\"12\" y2=\"12\"></line>\r\n");
      out.write("                        <line x1=\"12\" y1=\"8\" x2=\"12.01\" y2=\"8\"></line>\r\n");
      out.write("                    </svg>\r\n");
      out.write("                    <p class=\"insight-text\">");
      out.print( analysis.getInsightMessage() );
      out.write("</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
 if ("week".equals(currentView) && weekAnalyses != null && !weekAnalyses.isEmpty()) { 
      out.write("\r\n");
      out.write("        <!-- Weekly Overview -->\r\n");
      out.write("        <div class=\"weekly-overview-section\">\r\n");
      out.write("            <div class=\"section-header\">\r\n");
      out.write("                <h2 class=\"section-title\">Weekly Load Distribution</h2>\r\n");
      out.write("                <p class=\"section-subtitle\">Track your study load across the week</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"week-grid\">\r\n");
      out.write("                ");
 for (LoadAnalysis weekAnalysis : weekAnalyses) { 
      out.write("\r\n");
      out.write("                <div class=\"week-day-card\">\r\n");
      out.write("                    <div class=\"week-day-header\">\r\n");
      out.write("                        <div class=\"week-day-date\">");
      out.print( weekAnalysis.getAnalysisDate().format(dateFormatter) );
      out.write("</div>\r\n");
      out.write("                        <div class=\"week-day-status\">\r\n");
      out.write("                            <div class=\"status-dot ");
      out.print( weekAnalysis.getLoadCategory().toLowerCase() );
      out.write("\"></div>\r\n");
      out.write("                            <span class=\"status-label\">");
      out.print( weekAnalysis.getLoadCategory() );
      out.write("</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"week-day-metrics\">\r\n");
      out.write("                        <div class=\"metric\">\r\n");
      out.write("                            <div class=\"metric-number\">");
      out.print( weekAnalysis.getTotalEntries() );
      out.write("</div>\r\n");
      out.write("                            <div class=\"metric-label\">Subjects</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"metric\">\r\n");
      out.write("                            <div class=\"metric-number\">");
      out.print( weekAnalysis.getLoadScore() );
      out.write("</div>\r\n");
      out.write("                            <div class=\"metric-label\">Score</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"week-day-progress\">\r\n");
      out.write("                        <div class=\"progress-track\">\r\n");
      out.write("                            <div class=\"progress-fill ");
      out.print( weekAnalysis.getLoadCategory().toLowerCase() );
      out.write("\"\r\n");
      out.write("                                 style=\"width: ");
      out.print( Math.min(weekAnalysis.getLoadScore(), 100) );
      out.write("%;\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Load Entries Section -->\r\n");
      out.write("        <div class=\"load-entries-section\">\r\n");
      out.write("            <div class=\"section-header\">\r\n");
      out.write("                <h2 class=\"section-title\">\r\n");
      out.write("                    ");
      out.print( "week".equals(currentView) ? "All Subjects" : "Today's Subjects" );
      out.write("\r\n");
      out.write("                </h2>\r\n");
      out.write("                <p class=\"section-subtitle\">\r\n");
      out.write("                    ");
      out.print( "week".equals(currentView) ? "Manage all your study subjects" : "Your study subjects for today" );
      out.write("\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            ");
 if (loads != null && !loads.isEmpty()) { 
      out.write("\r\n");
      out.write("            <div class=\"load-entries-grid\">\r\n");
      out.write("                ");
 for (StudyLoad load : loads) { 
      out.write("\r\n");
      out.write("                <div class=\"load-entry-card\">\r\n");
      out.write("                    <div class=\"load-entry-header\">\r\n");
      out.write("                        <div class=\"subject-info\">\r\n");
      out.write("                            <h3 class=\"subject-name\">");
      out.print( load.getSubjectName() );
      out.write("</h3>\r\n");
      out.write("                            ");
 if ("week".equals(currentView)) { 
      out.write("\r\n");
      out.write("                            <div class=\"subject-date\">");
      out.print( load.getEntryDate().format(dateFormatter) );
      out.write("</div>\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"entry-actions\">\r\n");
      out.write("                            <button class=\"action-btn edit-btn\" aria-label=\"Edit\"\r\n");
      out.write("                                    data-entry-id=\"");
      out.print( load.getEntryId() );
      out.write("\"\r\n");
      out.write("                                    data-subject=\"");
      out.print( load.getSubjectName().replace("\"", "&quot;") );
      out.write("\"\r\n");
      out.write("                                    data-difficulty=\"");
      out.print( load.getDifficulty() );
      out.write("\"\r\n");
      out.write("                                    data-urgency=\"");
      out.print( load.getUrgency() );
      out.write("\"\r\n");
      out.write("                                    data-effort=\"");
      out.print( load.getEffort() );
      out.write("\"\r\n");
      out.write("                                    data-date=\"");
      out.print( load.getEntryDate() );
      out.write("\">\r\n");
      out.write("                                <svg class=\"action-icon\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                                    <path d=\"M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7\"></path>\r\n");
      out.write("                                    <path d=\"M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z\"></path>\r\n");
      out.write("                                </svg>\r\n");
      out.write("                            </button>\r\n");
      out.write("                            <button class=\"action-btn delete-btn\" aria-label=\"Delete\"\r\n");
      out.write("                                    data-entry-id=\"");
      out.print( load.getEntryId() );
      out.write("\">\r\n");
      out.write("                                <svg class=\"action-icon\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                                    <polyline points=\"3 6 5 6 21 6\"></polyline>\r\n");
      out.write("                                    <path d=\"M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2\"></path>\r\n");
      out.write("                                </svg>\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"load-entry-attributes\">\r\n");
      out.write("                        <div class=\"attribute-item\">\r\n");
      out.write("                            <span class=\"attribute-label\">Difficulty</span>\r\n");
      out.write("                            <span class=\"attribute-value difficulty-");
      out.print( load.getDifficulty().toLowerCase() );
      out.write("\">\r\n");
      out.write("                                ");
      out.print( load.getDifficulty() );
      out.write("\r\n");
      out.write("                            </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"attribute-item\">\r\n");
      out.write("                            <span class=\"attribute-label\">Urgency</span>\r\n");
      out.write("                            <span class=\"attribute-value urgency-");
      out.print( load.getUrgency().toLowerCase() );
      out.write("\">\r\n");
      out.write("                                ");
      out.print( load.getUrgency() );
      out.write("\r\n");
      out.write("                            </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"attribute-item\">\r\n");
      out.write("                            <span class=\"attribute-label\">Effort</span>\r\n");
      out.write("                            <span class=\"attribute-value effort-");
      out.print( load.getEffort().toLowerCase() );
      out.write("\">\r\n");
      out.write("                                ");
      out.print( load.getEffort() );
      out.write("\r\n");
      out.write("                            </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("            <!-- Empty State -->\r\n");
      out.write("            <div class=\"empty-state\">\r\n");
      out.write("                <div class=\"empty-state-icon\">\r\n");
      out.write("                    <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                        <rect x=\"3\" y=\"4\" width=\"18\" height=\"18\" rx=\"2\" ry=\"2\"></rect>\r\n");
      out.write("                        <line x1=\"16\" y1=\"2\" x2=\"16\" y2=\"6\"></line>\r\n");
      out.write("                        <line x1=\"8\" y1=\"2\" x2=\"8\" y2=\"6\"></line>\r\n");
      out.write("                        <line x1=\"3\" y1=\"10\" x2=\"21\" y2=\"10\"></line>\r\n");
      out.write("                    </svg>\r\n");
      out.write("                </div>\r\n");
      out.write("                <h3 class=\"empty-state-title\">No subjects yet</h3>\r\n");
      out.write("                <p class=\"empty-state-description\">\r\n");
      out.write("                    Add your first study subject to start balancing your academic workload intelligently.\r\n");
      out.write("                </p>\r\n");
      out.write("                <button onclick=\"openAddLoadModal()\" class=\"btn-primary\">\r\n");
      out.write("                    <svg class=\"btn-icon\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                        <path d=\"M12 5v14M5 12h14\"></path>\r\n");
      out.write("                    </svg>\r\n");
      out.write("                    Add Subject\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </main>\r\n");
      out.write("\r\n");
      out.write("    <!-- Add/Edit Modal -->\r\n");
      out.write("    <div id=\"loadModal\" class=\"modal-overlay\">\r\n");
      out.write("        <div class=\"modal-container\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <h2 id=\"modalTitle\" class=\"modal-title\">Add Subject</h2>\r\n");
      out.write("                <button class=\"modal-close-btn\" onclick=\"closeLoadModal()\" aria-label=\"Close\">\r\n");
      out.write("                    <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                        <line x1=\"18\" y1=\"6\" x2=\"6\" y2=\"18\"></line>\r\n");
      out.write("                        <line x1=\"6\" y1=\"6\" x2=\"18\" y2=\"18\"></line>\r\n");
      out.write("                    </svg>\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <form id=\"loadForm\" method=\"post\" action=\"load-balancer\" class=\"modal-form\">\r\n");
      out.write("                <input type=\"hidden\" name=\"action\" id=\"formAction\" value=\"add\">\r\n");
      out.write("                <input type=\"hidden\" name=\"entryId\" id=\"entryId\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-section\">\r\n");
      out.write("                    <div class=\"form-field\">\r\n");
      out.write("                        <label for=\"subjectName\" class=\"form-field-label\">Subject Name</label>\r\n");
      out.write("                        <input type=\"text\" id=\"subjectName\" name=\"subjectName\" class=\"form-field-input\"\r\n");
      out.write("                               placeholder=\"e.g., Mathematics, Physics, Chemistry\" required maxlength=\"200\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-section\">\r\n");
      out.write("                    <h3 class=\"form-section-title\">Subject Characteristics</h3>\r\n");
      out.write("                    <div class=\"form-grid\">\r\n");
      out.write("                        <div class=\"form-field\">\r\n");
      out.write("                            <label for=\"difficulty\" class=\"form-field-label\">Difficulty Level</label>\r\n");
      out.write("                            <select id=\"difficulty\" name=\"difficulty\" class=\"form-field-select\" required>\r\n");
      out.write("                                <option value=\"\">Select difficulty</option>\r\n");
      out.write("                                <option value=\"Easy\">Easy</option>\r\n");
      out.write("                                <option value=\"Medium\">Medium</option>\r\n");
      out.write("                                <option value=\"Hard\">Hard</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"form-field\">\r\n");
      out.write("                            <label for=\"urgency\" class=\"form-field-label\">Urgency Level</label>\r\n");
      out.write("                            <select id=\"urgency\" name=\"urgency\" class=\"form-field-select\" required>\r\n");
      out.write("                                <option value=\"\">Select urgency</option>\r\n");
      out.write("                                <option value=\"Low\">Low</option>\r\n");
      out.write("                                <option value=\"Medium\">Medium</option>\r\n");
      out.write("                                <option value=\"High\">High</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"form-field\">\r\n");
      out.write("                            <label for=\"effort\" class=\"form-field-label\">Effort Required</label>\r\n");
      out.write("                            <select id=\"effort\" name=\"effort\" class=\"form-field-select\" required>\r\n");
      out.write("                                <option value=\"\">Select effort</option>\r\n");
      out.write("                                <option value=\"Light\">Light</option>\r\n");
      out.write("                                <option value=\"Moderate\">Moderate</option>\r\n");
      out.write("                                <option value=\"Heavy\">Heavy</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"form-field\">\r\n");
      out.write("                            <label for=\"entryDate\" class=\"form-field-label\">Study Date <span class=\"optional\">(Optional)</span></label>\r\n");
      out.write("                            <input type=\"date\" id=\"entryDate\" name=\"entryDate\" class=\"form-field-input\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"modal-actions\">\r\n");
      out.write("                    <button type=\"button\" onclick=\"closeLoadModal()\" class=\"btn-secondary\">Cancel</button>\r\n");
      out.write("                    <button type=\"submit\" class=\"btn-primary\">Save Subject</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"js/theme.js\"></script>\r\n");
      out.write("    <script src=\"js/load-balancer.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
