/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.84
 * Generated at: 2025-12-26 03:36:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.whoami.model.*;

public final class mind_002dcheckin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.whoami.model");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Mind Check-In - WhoAmI</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");

        if (session.getAttribute("userId") == null) {
            response.sendRedirect("login");
            return;
        }
        String userName = (String) session.getAttribute("userName");
        MindLog existingLog = (MindLog) request.getAttribute("existingLog");
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "WEB-INF/navbar.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("activePage", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("mind-checkin", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("activeSection", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("mind", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("userName", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf( userName ), request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <main class=\"main-content\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <!-- Hero Section -->\r\n");
      out.write("            <div class=\"mind-checkin-hero\">\r\n");
      out.write("                <div class=\"hero-content\">\r\n");
      out.write("                    <div class=\"hero-icon\">\r\n");
      out.write("                        <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                            <circle cx=\"12\" cy=\"12\" r=\"10\"></circle>\r\n");
      out.write("                            <path d=\"M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3\"></path>\r\n");
      out.write("                            <line x1=\"12\" y1=\"17\" x2=\"12.01\" y2=\"17\"></line>\r\n");
      out.write("                        </svg>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"hero-text\">\r\n");
      out.write("                        <h1 class=\"hero-title\">Mind Check-In</h1>\r\n");
      out.write("                        <p class=\"hero-subtitle\">Take 60 seconds to understand your current mental state</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"hero-stats\">\r\n");
      out.write("                    <div class=\"stat-item\">\r\n");
      out.write("                        <div class=\"stat-number\">");
      out.print( existingLog != null ? "1" : "0" );
      out.write("</div>\r\n");
      out.write("                        <div class=\"stat-label\">Today's Check-ins</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"stat-item\">\r\n");
      out.write("                        <div class=\"stat-number\">5</div>\r\n");
      out.write("                        <div class=\"stat-label\">Questions</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            ");
 if (existingLog != null) { 
      out.write("\r\n");
      out.write("            <div class=\"alert-card alert-info\">\r\n");
      out.write("                <div class=\"alert-icon\">\r\n");
      out.write("                    <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                        <circle cx=\"12\" cy=\"12\" r=\"10\"></circle>\r\n");
      out.write("                        <line x1=\"12\" y1=\"16\" x2=\"12\" y2=\"12\"></line>\r\n");
      out.write("                        <line x1=\"12\" y1=\"8\" x2=\"12.01\" y2=\"8\"></line>\r\n");
      out.write("                    </svg>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"alert-content\">\r\n");
      out.write("                    <h3 class=\"alert-title\">Check-in Already Completed</h3>\r\n");
      out.write("                    <p class=\"alert-message\">You've already checked in today. You can update your responses below.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!-- Check-in Form -->\r\n");
      out.write("            <div class=\"checkin-card\">\r\n");
      out.write("                <form method=\"post\" action=\"mind-checkin\" class=\"checkin-form\">\r\n");
      out.write("                    <!-- Focus Level -->\r\n");
      out.write("                    <div class=\"question-section\">\r\n");
      out.write("                        <div class=\"question-header\">\r\n");
      out.write("                            <div class=\"question-number\">1</div>\r\n");
      out.write("                            <div class=\"question-content\">\r\n");
      out.write("                                <h3 class=\"question-title\">Focus Level</h3>\r\n");
      out.write("                                <p class=\"question-subtitle\">How focused do you feel right now?</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"options-grid\">\r\n");
      out.write("                            <label class=\"option-card ");
      out.print( existingLog != null && existingLog.getFocusLevel() == 1 ? "selected" : "" );
      out.write("\">\r\n");
      out.write("                                <input type=\"radio\" name=\"focus\" value=\"1\" ");
      out.print( existingLog != null && existingLog.getFocusLevel() == 1 ? "checked" : "" );
      out.write(" required>\r\n");
      out.write("                                <div class=\"option-content\">\r\n");
      out.write("                                    <div class=\"option-icon\">\r\n");
      out.write("                                        <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                                            <circle cx=\"12\" cy=\"12\" r=\"10\"></circle>\r\n");
      out.write("                                            <line x1=\"15\" y1=\"9\" x2=\"9\" y2=\"15\"></line>\r\n");
      out.write("                                            <line x1=\"9\" y1=\"9\" x2=\"15\" y2=\"15\"></line>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"option-text\">\r\n");
      out.write("                                        <div class=\"option-label\">1 - Scattered</div>\r\n");
      out.write("                                        <div class=\"option-desc\">Can't focus, mind wandering</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </label>\r\n");
      out.write("                            <label class=\"option-card ");
      out.print( existingLog != null && existingLog.getFocusLevel() == 2 ? "selected" : "" );
      out.write("\">\r\n");
      out.write("                                <input type=\"radio\" name=\"focus\" value=\"2\" ");
      out.print( existingLog != null && existingLog.getFocusLevel() == 2 ? "checked" : "" );
      out.write(" required>\r\n");
      out.write("                                <div class=\"option-content\">\r\n");
      out.write("                                    <div class=\"option-icon\">\r\n");
      out.write("                                        <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                                            <circle cx=\"12\" cy=\"12\" r=\"10\"></circle>\r\n");
      out.write("                                            <line x1=\"12\" y1=\"8\" x2=\"12\" y2=\"16\"></line>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"option-text\">\r\n");
      out.write("                                        <div class=\"option-label\">2 - Distracted</div>\r\n");
      out.write("                                        <div class=\"option-desc\">Some focus but easily sidetracked</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </label>\r\n");
      out.write("                            <label class=\"option-card ");
      out.print( existingLog != null && existingLog.getFocusLevel() == 3 ? "selected" : "" );
      out.write("\">\r\n");
      out.write("                                <input type=\"radio\" name=\"focus\" value=\"3\" ");
      out.print( existingLog != null && existingLog.getFocusLevel() == 3 ? "checked" : "" );
      out.write(" required>\r\n");
      out.write("                                <div class=\"option-content\">\r\n");
      out.write("                                    <div class=\"option-icon\">\r\n");
      out.write("                                        <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                                            <circle cx=\"12\" cy=\"12\" r=\"10\"></circle>\r\n");
      out.write("                                            <path d=\"M12 8v4l2 2\"></path>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"option-text\">\r\n");
      out.write("                                        <div class=\"option-label\">3 - Moderate</div>\r\n");
      out.write("                                        <div class=\"option-desc\">Decent focus with occasional lapses</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </label>\r\n");
      out.write("                            <label class=\"option-card ");
      out.print( existingLog != null && existingLog.getFocusLevel() == 4 ? "selected" : "" );
      out.write("\">\r\n");
      out.write("                                <input type=\"radio\" name=\"focus\" value=\"4\" ");
      out.print( existingLog != null && existingLog.getFocusLevel() == 4 ? "checked" : "" );
      out.write(" required>\r\n");
      out.write("                                <div class=\"option-content\">\r\n");
      out.write("                                    <div class=\"option-icon\">\r\n");
      out.write("                                        <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                                            <circle cx=\"12\" cy=\"12\" r=\"10\"></circle>\r\n");
      out.write("                                            <polyline points=\"12,6 12,12 16,10\"></polyline>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"option-text\">\r\n");
      out.write("                                        <div class=\"option-label\">4 - Focused</div>\r\n");
      out.write("                                        <div class=\"option-desc\">Good concentration, productive</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </label>\r\n");
      out.write("                            <label class=\"option-card ");
      out.print( existingLog != null && existingLog.getFocusLevel() == 5 ? "selected" : "" );
      out.write("\">\r\n");
      out.write("                                <input type=\"radio\" name=\"focus\" value=\"5\" ");
      out.print( existingLog != null && existingLog.getFocusLevel() == 5 ? "checked" : "" );
      out.write(" required>\r\n");
      out.write("                                <div class=\"option-content\">\r\n");
      out.write("                                    <div class=\"option-icon\">\r\n");
      out.write("                                        <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                                            <circle cx=\"12\" cy=\"12\" r=\"10\"></circle>\r\n");
      out.write("                                            <path d=\"M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z\"></path>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"option-text\">\r\n");
      out.write("                                        <div class=\"option-label\">5 - Laser Sharp</div>\r\n");
      out.write("                                        <div class=\"option-desc\">Peak focus, highly productive</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Energy Level -->\r\n");
      out.write("                    <div class=\"question-section\">\r\n");
      out.write("                        <div class=\"question-header\">\r\n");
      out.write("                            <div class=\"question-number\">2</div>\r\n");
      out.write("                            <div class=\"question-content\">\r\n");
      out.write("                                <h3 class=\"question-title\">Energy Level</h3>\r\n");
      out.write("                                <p class=\"question-subtitle\">How energetic do you feel physically?</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"options-grid\">\r\n");
      out.write("                            <label class=\"option-card ");
      out.print( existingLog != null && existingLog.getEnergyLevel() == 1 ? "selected" : "" );
      out.write("\">\r\n");
      out.write("                                <input type=\"radio\" name=\"energy\" value=\"1\" ");
      out.print( existingLog != null && existingLog.getEnergyLevel() == 1 ? "checked" : "" );
      out.write(" required>\r\n");
      out.write("                                <div class=\"option-content\">\r\n");
      out.write("                                    <div class=\"option-icon exhausted\">\r\n");
      out.write("                                        <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                                            <path d=\"M12 2l-1 7h2l-1-7z\"></path>\r\n");
      out.write("                                            <path d=\"M12 9c-1.5 0-3 1-3 3 0 1.5 1 3 3 3s3-1.5 3-3c0-2-1.5-3-3-3z\"></path>\r\n");
      out.write("                                            <path d=\"M8 22l8-8\"></path>\r\n");
      out.write("                                            <path d=\"M16 22l-8-8\"></path>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"option-text\">\r\n");
      out.write("                                        <div class=\"option-label\">1 - Exhausted</div>\r\n");
      out.write("                                        <div class=\"option-desc\">No energy, completely drained</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </label>\r\n");
      out.write("                            <label class=\"option-card ");
      out.print( existingLog != null && existingLog.getEnergyLevel() == 2 ? "selected" : "" );
      out.write("\">\r\n");
      out.write("                                <input type=\"radio\" name=\"energy\" value=\"2\" ");
      out.print( existingLog != null && existingLog.getEnergyLevel() == 2 ? "checked" : "" );
      out.write(" required>\r\n");
      out.write("                                <div class=\"option-content\">\r\n");
      out.write("                                    <div class=\"option-icon low\">\r\n");
      out.write("                                        <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                                            <circle cx=\"12\" cy=\"12\" r=\"10\"></circle>\r\n");
      out.write("                                            <line x1=\"12\" y1=\"8\" x2=\"12\" y2=\"12\"></line>\r\n");
      out.write("                                            <line x1=\"12\" y1=\"16\" x2=\"12.01\" y2=\"16\"></line>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"option-text\">\r\n");
      out.write("                                        <div class=\"option-label\">2 - Low</div>\r\n");
      out.write("                                        <div class=\"option-desc\">Tired, need rest soon</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </label>\r\n");
      out.write("                            <label class=\"option-card ");
      out.print( existingLog != null && existingLog.getEnergyLevel() == 3 ? "selected" : "" );
      out.write("\">\r\n");
      out.write("                                <input type=\"radio\" name=\"energy\" value=\"3\" ");
      out.print( existingLog != null && existingLog.getEnergyLevel() == 3 ? "checked" : "" );
      out.write(" required>\r\n");
      out.write("                                <div class=\"option-content\">\r\n");
      out.write("                                    <div class=\"option-icon moderate\">\r\n");
      out.write("                                        <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                                            <circle cx=\"12\" cy=\"12\" r=\"10\"></circle>\r\n");
      out.write("                                            <path d=\"M12 8v4\"></path>\r\n");
      out.write("                                            <path d=\"M12 16h.01\"></path>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"option-text\">\r\n");
      out.write("                                        <div class=\"option-label\">3 - Moderate</div>\r\n");
      out.write("                                        <div class=\"option-desc\">Steady energy, manageable</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </label>\r\n");
      out.write("                            <label class=\"option-card ");
      out.print( existingLog != null && existingLog.getEnergyLevel() == 4 ? "selected" : "" );
      out.write("\">\r\n");
      out.write("                                <input type=\"radio\" name=\"energy\" value=\"4\" ");
      out.print( existingLog != null && existingLog.getEnergyLevel() == 4 ? "checked" : "" );
      out.write(" required>\r\n");
      out.write("                                <div class=\"option-content\">\r\n");
      out.write("                                    <div class=\"option-icon good\">\r\n");
      out.write("                                        <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                                            <circle cx=\"12\" cy=\"12\" r=\"10\"></circle>\r\n");
      out.write("                                            <path d=\"M8 14l2 2 4-4\"></path>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"option-text\">\r\n");
      out.write("                                        <div class=\"option-label\">4 - Good</div>\r\n");
      out.write("                                        <div class=\"option-desc\">Energetic, feeling good</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </label>\r\n");
      out.write("                            <label class=\"option-card ");
      out.print( existingLog != null && existingLog.getEnergyLevel() == 5 ? "selected" : "" );
      out.write("\">\r\n");
      out.write("                                <input type=\"radio\" name=\"energy\" value=\"5\" ");
      out.print( existingLog != null && existingLog.getEnergyLevel() == 5 ? "checked" : "" );
      out.write(" required>\r\n");
      out.write("                                <div class=\"option-content\">\r\n");
      out.write("                                    <div class=\"option-icon high\">\r\n");
      out.write("                                        <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                                            <path d=\"M13 2L3 14h9l-1 8 10-12h-9l1-8z\"></path>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"option-text\">\r\n");
      out.write("                                        <div class=\"option-label\">5 - Energized</div>\r\n");
      out.write("                                        <div class=\"option-desc\">High energy, ready to go</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Emotional Load -->\r\n");
      out.write("                    <div class=\"question-section\">\r\n");
      out.write("                        <div class=\"question-header\">\r\n");
      out.write("                            <div class=\"question-number\">3</div>\r\n");
      out.write("                            <div class=\"question-content\">\r\n");
      out.write("                                <h3 class=\"question-title\">Emotional Load</h3>\r\n");
      out.write("                                <p class=\"question-subtitle\">How emotionally burdened do you feel?</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"options-grid\">\r\n");
      out.write("                            <label class=\"option-card ");
      out.print( existingLog != null && existingLog.getEmotionalLoad() == 1 ? "selected" : "" );
      out.write("\">\r\n");
      out.write("                                <input type=\"radio\" name=\"emotional\" value=\"1\" ");
      out.print( existingLog != null && existingLog.getEmotionalLoad() == 1 ? "checked" : "" );
      out.write(" required>\r\n");
      out.write("                                <div class=\"option-content\">\r\n");
      out.write("                                    <div class=\"option-icon light\">\r\n");
      out.write("                                        <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                                            <path d=\"M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z\"></path>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"option-text\">\r\n");
      out.write("                                        <div class=\"option-label\">1 - Light</div>\r\n");
      out.write("                                        <div class=\"option-desc\">Emotionally free, at peace</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </label>\r\n");
      out.write("                            <label class=\"option-card ");
      out.print( existingLog != null && existingLog.getEmotionalLoad() == 2 ? "selected" : "" );
      out.write("\">\r\n");
      out.write("                                <input type=\"radio\" name=\"emotional\" value=\"2\" ");
      out.print( existingLog != null && existingLog.getEmotionalLoad() == 2 ? "checked" : "" );
      out.write(" required>\r\n");
      out.write("                                <div class=\"option-content\">\r\n");
      out.write("                                    <div class=\"option-icon light\">\r\n");
      out.write("                                        <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                                            <circle cx=\"12\" cy=\"12\" r=\"10\"></circle>\r\n");
      out.write("                                            <path d=\"M8 14s1.5 2 4 2 4-2 4-2\"></path>\r\n");
      out.write("                                            <line x1=\"9\" y1=\"9\" x2=\"9.01\" y2=\"9\"></line>\r\n");
      out.write("                                            <line x1=\"15\" y1=\"9\" x2=\"15.01\" y2=\"9\"></line>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"option-text\">\r\n");
      out.write("                                        <div class=\"option-label\">2 - Mild</div>\r\n");
      out.write("                                        <div class=\"option-desc\">Some emotions, manageable</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </label>\r\n");
      out.write("                            <label class=\"option-card ");
      out.print( existingLog != null && existingLog.getEmotionalLoad() == 3 ? "selected" : "" );
      out.write("\">\r\n");
      out.write("                                <input type=\"radio\" name=\"emotional\" value=\"3\" ");
      out.print( existingLog != null && existingLog.getEmotionalLoad() == 3 ? "checked" : "" );
      out.write(" required>\r\n");
      out.write("                                <input type=\"radio\" name=\"emotional\" value=\"3\" ");
      out.print( existingLog != null && existingLog.getEmotionalLoad() == 3 ? "checked" : "" );
      out.write(">\r\n");
      out.write("                                <div class=\"option-content\">\r\n");
      out.write("                                    <div class=\"option-icon moderate\">\r\n");
      out.write("                                        <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                                            <circle cx=\"12\" cy=\"12\" r=\"10\"></circle>\r\n");
      out.write("                                            <line x1=\"8\" y1=\"15\" x2=\"8\" y2=\"17\"></line>\r\n");
      out.write("                                            <line x1=\"16\" y1=\"15\" x2=\"16\" y2=\"17\"></line>\r\n");
      out.write("                                            <path d=\"M12 9c1.5 0 3 1 3 3 0 1-1 2-3 2s-3-1-3-2c0-2 1.5-3 3-3z\"></path>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"option-text\">\r\n");
      out.write("                                        <div class=\"option-label\">3 - Moderate</div>\r\n");
      out.write("                                        <div class=\"option-desc\">Noticeable emotional weight</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </label>\r\n");
      out.write("                            <label class=\"option-card ");
      out.print( existingLog != null && existingLog.getEmotionalLoad() == 4 ? "selected" : "" );
      out.write("\">\r\n");
      out.write("                                <input type=\"radio\" name=\"emotional\" value=\"4\" ");
      out.print( existingLog != null && existingLog.getEmotionalLoad() == 4 ? "checked" : "" );
      out.write(" required>\r\n");
      out.write("                                <div class=\"option-content\">\r\n");
      out.write("                                    <div class=\"option-icon heavy\">\r\n");
      out.write("                                        <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                                            <circle cx=\"12\" cy=\"12\" r=\"10\"></circle>\r\n");
      out.write("                                            <path d=\"M16 16c-1.5 1.5-4 1.5-5.5 0S7 12.5 8.5 11 12 10.5 16 12s1.5 3.5 0 4z\"></path>\r\n");
      out.write("                                            <line x1=\"9\" y1=\"9\" x2=\"9.01\" y2=\"9\"></line>\r\n");
      out.write("                                            <line x1=\"15\" y1=\"9\" x2=\"15.01\" y2=\"9\"></line>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"option-text\">\r\n");
      out.write("                                        <div class=\"option-label\">4 - Heavy</div>\r\n");
      out.write("                                        <div class=\"option-desc\">Strong emotional burden</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </label>\r\n");
      out.write("                            <label class=\"option-card ");
      out.print( existingLog != null && existingLog.getEmotionalLoad() == 5 ? "selected" : "" );
      out.write("\">\r\n");
      out.write("                                <input type=\"radio\" name=\"emotional\" value=\"5\" ");
      out.print( existingLog != null && existingLog.getEmotionalLoad() == 5 ? "checked" : "" );
      out.write(" required>\r\n");
      out.write("                                <div class=\"option-content\">\r\n");
      out.write("                                    <div class=\"option-icon heavy\">\r\n");
      out.write("                                        <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                                            <path d=\"M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 15l-5-5 1.41-1.41L10 14.17l7.59-7.59L19 8l-9 9z\"></path>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"option-text\">\r\n");
      out.write("                                        <div class=\"option-label\">5 - Overwhelming</div>\r\n");
      out.write("                                        <div class=\"option-desc\">Emotionally overwhelmed</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Mental Clarity -->\r\n");
      out.write("                    <div class=\"question-section\">\r\n");
      out.write("                        <div class=\"question-header\">\r\n");
      out.write("                            <div class=\"question-number\">4</div>\r\n");
      out.write("                            <div class=\"question-content\">\r\n");
      out.write("                                <h3 class=\"question-title\">Mental Clarity</h3>\r\n");
      out.write("                                <p class=\"question-subtitle\">How clear is your thinking right now?</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"options-grid\">\r\n");
      out.write("                            <label class=\"option-card ");
      out.print( existingLog != null && existingLog.getClarityLevel() == 1 ? "selected" : "" );
      out.write("\">\r\n");
      out.write("                                <input type=\"radio\" name=\"clarity\" value=\"1\" ");
      out.print( existingLog != null && existingLog.getClarityLevel() == 1 ? "checked" : "" );
      out.write(" required>\r\n");
      out.write("                                <div class=\"option-content\">\r\n");
      out.write("                                    <div class=\"option-icon foggy\">\r\n");
      out.write("                                        <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                                            <path d=\"M3 15a4 4 0 0 1 4-4h1a5 5 0 0 1 5 5v1a4 4 0 0 1-4 4H7a4 4 0 0 1-4-4z\"></path>\r\n");
      out.write("                                            <path d=\"M7 9a4 4 0 0 1 4-4h1a5 5 0 0 1 5 5v1a4 4 0 0 1-4 4\"></path>\r\n");
      out.write("                                            <path d=\"M11 3a4 4 0 0 1 4-4h1a5 5 0 0 1 5 5v1a4 4 0 0 1-4 4\"></path>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"option-text\">\r\n");
      out.write("                                        <div class=\"option-label\">1 - Foggy</div>\r\n");
      out.write("                                        <div class=\"option-desc\">Confused, unclear thinking</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </label>\r\n");
      out.write("                            <label class=\"option-card ");
      out.print( existingLog != null && existingLog.getClarityLevel() == 2 ? "selected" : "" );
      out.write("\">\r\n");
      out.write("                                <input type=\"radio\" name=\"clarity\" value=\"2\" ");
      out.print( existingLog != null && existingLog.getClarityLevel() == 2 ? "checked" : "" );
      out.write(" required>\r\n");
      out.write("                                <div class=\"option-content\">\r\n");
      out.write("                                    <div class=\"option-icon foggy\">\r\n");
      out.write("                                        <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                                            <circle cx=\"12\" cy=\"12\" r=\"10\"></circle>\r\n");
      out.write("                                            <line x1=\"12\" y1=\"8\" x2=\"12\" y2=\"12\"></line>\r\n");
      out.write("                                            <line x1=\"12\" y1=\"16\" x2=\"12.01\" y2=\"16\"></line>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"option-text\">\r\n");
      out.write("                                        <div class=\"option-label\">2 - Hazy</div>\r\n");
      out.write("                                        <div class=\"option-desc\">Some confusion, not sharp</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </label>\r\n");
      out.write("                            <label class=\"option-card ");
      out.print( existingLog != null && existingLog.getClarityLevel() == 3 ? "selected" : "" );
      out.write("\">\r\n");
      out.write("                                <input type=\"radio\" name=\"clarity\" value=\"3\" ");
      out.print( existingLog != null && existingLog.getClarityLevel() == 3 ? "checked" : "" );
      out.write(" required>\r\n");
      out.write("                                <div class=\"option-content\">\r\n");
      out.write("                                    <div class=\"option-icon moderate\">\r\n");
      out.write("                                        <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                                            <circle cx=\"12\" cy=\"12\" r=\"10\"></circle>\r\n");
      out.write("                                            <path d=\"M12 8v4\"></path>\r\n");
      out.write("                                            <path d=\"M12 16h.01\"></path>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"option-text\">\r\n");
      out.write("                                        <div class=\"option-label\">3 - Moderate</div>\r\n");
      out.write("                                        <div class=\"option-desc\">Decent clarity, functional</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </label>\r\n");
      out.write("                            <label class=\"option-card ");
      out.print( existingLog != null && existingLog.getClarityLevel() == 4 ? "selected" : "" );
      out.write("\">\r\n");
      out.write("                                <input type=\"radio\" name=\"clarity\" value=\"4\" ");
      out.print( existingLog != null && existingLog.getClarityLevel() == 4 ? "checked" : "" );
      out.write(" required>\r\n");
      out.write("                                <div class=\"option-content\">\r\n");
      out.write("                                    <div class=\"option-icon clear\">\r\n");
      out.write("                                        <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                                            <circle cx=\"12\" cy=\"12\" r=\"10\"></circle>\r\n");
      out.write("                                            <path d=\"M9 12l2 2 4-4\"></path>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"option-text\">\r\n");
      out.write("                                        <div class=\"option-label\">4 - Clear</div>\r\n");
      out.write("                                        <div class=\"option-desc\">Good mental clarity</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </label>\r\n");
      out.write("                            <label class=\"option-card ");
      out.print( existingLog != null && existingLog.getClarityLevel() == 5 ? "selected" : "" );
      out.write("\">\r\n");
      out.write("                                <input type=\"radio\" name=\"clarity\" value=\"5\" ");
      out.print( existingLog != null && existingLog.getClarityLevel() == 5 ? "checked" : "" );
      out.write(" required>\r\n");
      out.write("                                <div class=\"option-content\">\r\n");
      out.write("                                    <div class=\"option-icon clear\">\r\n");
      out.write("                                        <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                                            <path d=\"M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z\"></path>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"option-text\">\r\n");
      out.write("                                        <div class=\"option-label\">5 - Crystal Clear</div>\r\n");
      out.write("                                        <div class=\"option-desc\">Exceptional mental clarity</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Stress Level -->\r\n");
      out.write("                    <div class=\"question-section\">\r\n");
      out.write("                        <div class=\"question-header\">\r\n");
      out.write("                            <div class=\"question-number\">5</div>\r\n");
      out.write("                            <div class=\"question-content\">\r\n");
      out.write("                                <h3 class=\"question-title\">Stress Level</h3>\r\n");
      out.write("                                <p class=\"question-subtitle\">How stressed do you feel right now?</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"options-grid\">\r\n");
      out.write("                            <label class=\"option-card ");
      out.print( existingLog != null && existingLog.getStressLevel() == 1 ? "selected" : "" );
      out.write("\">\r\n");
      out.write("                                <input type=\"radio\" name=\"stress\" value=\"1\" ");
      out.print( existingLog != null && existingLog.getStressLevel() == 1 ? "checked" : "" );
      out.write(" required>\r\n");
      out.write("                                <div class=\"option-content\">\r\n");
      out.write("                                    <div class=\"option-icon calm\">\r\n");
      out.write("                                        <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                                            <path d=\"M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z\"></path>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"option-text\">\r\n");
      out.write("                                        <div class=\"option-label\">1 - Calm</div>\r\n");
      out.write("                                        <div class=\"option-desc\">Completely relaxed, no stress</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </label>\r\n");
      out.write("                            <label class=\"option-card ");
      out.print( existingLog != null && existingLog.getStressLevel() == 2 ? "selected" : "" );
      out.write("\">\r\n");
      out.write("                                <input type=\"radio\" name=\"stress\" value=\"2\" ");
      out.print( existingLog != null && existingLog.getStressLevel() == 2 ? "checked" : "" );
      out.write(" required>\r\n");
      out.write("                                <div class=\"option-content\">\r\n");
      out.write("                                    <div class=\"option-icon calm\">\r\n");
      out.write("                                        <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                                            <circle cx=\"12\" cy=\"12\" r=\"10\"></circle>\r\n");
      out.write("                                            <path d=\"M8 14s1.5 2 4 2 4-2 4-2\"></path>\r\n");
      out.write("                                            <line x1=\"9\" y1=\"9\" x2=\"9.01\" y2=\"9\"></line>\r\n");
      out.write("                                            <line x1=\"15\" y1=\"9\" x2=\"15.01\" y2=\"9\"></line>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"option-text\">\r\n");
      out.write("                                        <div class=\"option-label\">2 - Mild</div>\r\n");
      out.write("                                        <div class=\"option-desc\">Minimal stress, manageable</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </label>\r\n");
      out.write("                            <label class=\"option-card ");
      out.print( existingLog != null && existingLog.getStressLevel() == 3 ? "selected" : "" );
      out.write("\">\r\n");
      out.write("                                <input type=\"radio\" name=\"stress\" value=\"3\" ");
      out.print( existingLog != null && existingLog.getStressLevel() == 3 ? "checked" : "" );
      out.write(" required>\r\n");
      out.write("                                <div class=\"option-content\">\r\n");
      out.write("                                    <div class=\"option-icon moderate\">\r\n");
      out.write("                                        <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                                            <circle cx=\"12\" cy=\"12\" r=\"10\"></circle>\r\n");
      out.write("                                            <line x1=\"8\" y1=\"15\" x2=\"8\" y2=\"17\"></line>\r\n");
      out.write("                                            <line x1=\"16\" y1=\"15\" x2=\"16\" y2=\"17\"></line>\r\n");
      out.write("                                            <path d=\"M12 9c1.5 0 3 1 3 3 0 1-1 2-3 2s-3-1-3-2c0-2 1.5-3 3-3z\"></path>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"option-text\">\r\n");
      out.write("                                        <div class=\"option-label\">3 - Moderate</div>\r\n");
      out.write("                                        <div class=\"option-desc\">Noticeable stress, handling it</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </label>\r\n");
      out.write("                            <label class=\"option-card ");
      out.print( existingLog != null && existingLog.getStressLevel() == 4 ? "selected" : "" );
      out.write("\">\r\n");
      out.write("                                <input type=\"radio\" name=\"stress\" value=\"4\" ");
      out.print( existingLog != null && existingLog.getStressLevel() == 4 ? "checked" : "" );
      out.write(" required>\r\n");
      out.write("                                <div class=\"option-content\">\r\n");
      out.write("                                    <div class=\"option-icon stressed\">\r\n");
      out.write("                                        <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                                            <circle cx=\"12\" cy=\"12\" r=\"10\"></circle>\r\n");
      out.write("                                            <path d=\"M16 16c-1.5 1.5-4 1.5-5.5 0S7 12.5 8.5 11 12 10.5 16 12s1.5 3.5 0 4z\"></path>\r\n");
      out.write("                                            <line x1=\"9\" y1=\"9\" x2=\"9.01\" y2=\"9\"></line>\r\n");
      out.write("                                            <line x1=\"15\" y1=\"9\" x2=\"15.01\" y2=\"9\"></line>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"option-text\">\r\n");
      out.write("                                        <div class=\"option-label\">4 - High</div>\r\n");
      out.write("                                        <div class=\"option-desc\">Significant stress, challenging</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </label>\r\n");
      out.write("                            <label class=\"option-card ");
      out.print( existingLog != null && existingLog.getStressLevel() == 5 ? "selected" : "" );
      out.write("\">\r\n");
      out.write("                                <input type=\"radio\" name=\"stress\" value=\"5\" ");
      out.print( existingLog != null && existingLog.getStressLevel() == 5 ? "checked" : "" );
      out.write(" required>\r\n");
      out.write("                                <div class=\"option-content\">\r\n");
      out.write("                                    <div class=\"option-icon stressed\">\r\n");
      out.write("                                        <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                                            <path d=\"M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z\"></path>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"option-text\">\r\n");
      out.write("                                        <div class=\"option-label\">5 - Overwhelmed</div>\r\n");
      out.write("                                        <div class=\"option-desc\">Extremely stressed, overwhelming</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Submit Button -->\r\n");
      out.write("                    <div class=\"form-actions\">\r\n");
      out.write("                        <button type=\"submit\" class=\"btn-primary-large\">\r\n");
      out.write("                            <svg class=\"btn-icon\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                                <path d=\"M9 12l2 2 4-4\"></path>\r\n");
      out.write("                                <path d=\"M21 12c-1 0-3-1-3-3s2-3 3-3\"></path>\r\n");
      out.write("                                <path d=\"M3 12c1 0 3-1 3-3s-2-3-3-3\"></path>\r\n");
      out.write("                                <path d=\"M12 3c-1 0-3 1-3 3s2 3 3 3\"></path>\r\n");
      out.write("                                <path d=\"M12 21c1 0 3-1 3-3s-2-3-3-3\"></path>\r\n");
      out.write("                            </svg>\r\n");
      out.write("                            ");
      out.print( existingLog != null ? "Update Check-In" : "Complete Check-In" );
      out.write("\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </main>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"js/theme.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("            // Handle option card selection\r\n");
      out.write("            const optionCards = document.querySelectorAll('.option-card');\r\n");
      out.write("            optionCards.forEach(card => {\r\n");
      out.write("                card.addEventListener('click', function() {\r\n");
      out.write("                    // Find the radio button inside this card\r\n");
      out.write("                    const radio = this.querySelector('input[type=\"radio\"]');\r\n");
      out.write("                    if (radio) {\r\n");
      out.write("                        radio.checked = true;\r\n");
      out.write("                        // Remove selected class from siblings in the same question\r\n");
      out.write("                        const questionSection = this.closest('.question-section');\r\n");
      out.write("                        questionSection.querySelectorAll('.option-card').forEach(c => {\r\n");
      out.write("                            c.classList.remove('selected');\r\n");
      out.write("                        });\r\n");
      out.write("                        // Add selected class to clicked card\r\n");
      out.write("                        this.classList.add('selected');\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            // Also handle radio button changes\r\n");
      out.write("            const radioButtons = document.querySelectorAll('input[type=\"radio\"]');\r\n");
      out.write("            radioButtons.forEach(radio => {\r\n");
      out.write("                radio.addEventListener('change', function() {\r\n");
      out.write("                    if (this.checked) {\r\n");
      out.write("                        // Remove selected class from siblings\r\n");
      out.write("                        const questionSection = this.closest('.question-section');\r\n");
      out.write("                        questionSection.querySelectorAll('.option-card').forEach(c => {\r\n");
      out.write("                            c.classList.remove('selected');\r\n");
      out.write("                        });\r\n");
      out.write("                        // Add selected class to parent card\r\n");
      out.write("                        this.closest('.option-card').classList.add('selected');\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
