/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.84
 * Generated at: 2025-12-24 11:23:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.whoami.model.*;
import java.util.*;
import java.text.SimpleDateFormat;

public final class task_002dzone_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.whoami.model");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Task & Routine Zone - WhoAmI</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");
 
        if (session.getAttribute("userId") == null) {
            response.sendRedirect("login");
            return;
        }
        String userName = (String) session.getAttribute("userName");
        List<Task> tasks = (List<Task>) request.getAttribute("tasks");
        List<Category> categories = (List<Category>) request.getAttribute("categories");
        TaskEfficiency efficiency = (TaskEfficiency) request.getAttribute("efficiency");
        String currentView = (String) request.getAttribute("currentView");
        String pageTitle = (String) request.getAttribute("pageTitle");
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm");
        SimpleDateFormat displayDateFormat = new SimpleDateFormat("MMM dd");
    
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <nav class=\"navbar\">\r\n");
      out.write("        <div class=\"container navbar-content\">\r\n");
      out.write("            <a href=\"dashboard\" class=\"navbar-brand\">WhoAmI</a>\r\n");
      out.write("            <div class=\"navbar-menu\">\r\n");
      out.write("                <a href=\"dashboard\" class=\"navbar-link\">Dashboard</a>\r\n");
      out.write("                <div class=\"navbar-dropdown\">\r\n");
      out.write("                    <button class=\"navbar-dropdown-toggle active\">\r\n");
      out.write("                        My Tasks\r\n");
      out.write("                        <svg class=\"navbar-dropdown-icon\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                            <polyline points=\"6 9 12 15 18 9\"></polyline>\r\n");
      out.write("                        </svg>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <div class=\"navbar-dropdown-menu\">\r\n");
      out.write("                        <a href=\"task-zone\" class=\"navbar-dropdown-item active\">Task Zone</a>\r\n");
      out.write("                        <a href=\"load-balancer\" class=\"navbar-dropdown-item\">Load Balancer</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"navbar-dropdown\">\r\n");
      out.write("                    <button class=\"navbar-dropdown-toggle\">\r\n");
      out.write("                        My Mind\r\n");
      out.write("                        <svg class=\"navbar-dropdown-icon\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                            <polyline points=\"6 9 12 15 18 9\"></polyline>\r\n");
      out.write("                        </svg>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <div class=\"navbar-dropdown-menu\">\r\n");
      out.write("                        <a href=\"mind-checkin\" class=\"navbar-dropdown-item\">Mind Check-In</a>\r\n");
      out.write("                        <a href=\"study-zone\" class=\"navbar-dropdown-item\">Study Zone</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"navbar-dropdown\">\r\n");
      out.write("                    <button class=\"navbar-dropdown-toggle\">\r\n");
      out.write("                        My Growth\r\n");
      out.write("                        <svg class=\"navbar-dropdown-icon\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\">\r\n");
      out.write("                            <polyline points=\"6 9 12 15 18 9\"></polyline>\r\n");
      out.write("                        </svg>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <div class=\"navbar-dropdown-menu\">\r\n");
      out.write("                        <a href=\"growth-timeline\" class=\"navbar-dropdown-item\">Growth Timeline</a>\r\n");
      out.write("                        <a href=\"insights\" class=\"navbar-dropdown-item\">Insights</a>\r\n");
      out.write("                        <a href=\"reflection\" class=\"navbar-dropdown-item\">Reflection</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"navbar-user\">\r\n");
      out.write("                <span class=\"user-name\">");
      out.print( userName );
      out.write("</span>\r\n");
      out.write("                <button class=\"theme-toggle\" onclick=\"toggleTheme()\" aria-label=\"Toggle theme\">\r\n");
      out.write("                    <svg id=\"theme-icon\" class=\"theme-icon\" viewBox=\"0 0 24 24\" fill=\"currentColor\">\r\n");
      out.write("                        <path d=\"M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z\"></path>\r\n");
      out.write("                    </svg>\r\n");
      out.write("                </button>\r\n");
      out.write("                <a href=\"logout\" class=\"btn btn-secondary\" style=\"padding: 8px 16px; font-size: 14px;\">Logout</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    \r\n");
      out.write("    <main class=\"main-content\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"page-header\">\r\n");
      out.write("                <h1 class=\"page-title\">Task & Routine Zone</h1>\r\n");
      out.write("                <p class=\"page-subtitle\">Master your day with intentional task management</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"grid grid-3\" style=\"margin-bottom: 32px;\">\r\n");
      out.write("                <div class=\"card efficiency-card\">\r\n");
      out.write("                    <div class=\"efficiency-header\">\r\n");
      out.write("                        <h3 class=\"efficiency-title\">Daily Efficiency</h3>\r\n");
      out.write("                        <div class=\"efficiency-percentage ");
      out.print( efficiency.getDailyEfficiency() >= 80 ? "excellent" : efficiency.getDailyEfficiency() >= 60 ? "great" : efficiency.getDailyEfficiency() >= 40 ? "good" : "fair" );
      out.write("\">\r\n");
      out.write("                            ");
      out.print( String.format("%.0f%%", efficiency.getDailyEfficiency()) );
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"efficiency-bar-container\">\r\n");
      out.write("                        <div class=\"efficiency-bar\">\r\n");
      out.write("                            <div class=\"efficiency-bar-fill ");
      out.print( efficiency.getDailyEfficiency() >= 80 ? "excellent" : efficiency.getDailyEfficiency() >= 60 ? "great" : efficiency.getDailyEfficiency() >= 40 ? "good" : "fair" );
      out.write("\" \r\n");
      out.write("                                 style=\"width: ");
      out.print( efficiency.getDailyEfficiency() );
      out.write("%\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p class=\"efficiency-label\">");
      out.print( efficiency.getEfficiencyLevel() );
      out.write("</p>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card efficiency-card\">\r\n");
      out.write("                    <div class=\"efficiency-header\">\r\n");
      out.write("                        <h3 class=\"efficiency-title\">Weekly Efficiency</h3>\r\n");
      out.write("                        <div class=\"efficiency-percentage ");
      out.print( efficiency.getWeeklyEfficiency() >= 80 ? "excellent" : efficiency.getWeeklyEfficiency() >= 60 ? "great" : efficiency.getWeeklyEfficiency() >= 40 ? "good" : "fair" );
      out.write("\">\r\n");
      out.write("                            ");
      out.print( String.format("%.0f%%", efficiency.getWeeklyEfficiency()) );
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"efficiency-bar-container\">\r\n");
      out.write("                        <div class=\"efficiency-bar\">\r\n");
      out.write("                            <div class=\"efficiency-bar-fill ");
      out.print( efficiency.getWeeklyEfficiency() >= 80 ? "excellent" : efficiency.getWeeklyEfficiency() >= 60 ? "great" : efficiency.getWeeklyEfficiency() >= 40 ? "good" : "fair" );
      out.write("\" \r\n");
      out.write("                                 style=\"width: ");
      out.print( efficiency.getWeeklyEfficiency() );
      out.write("%\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p class=\"efficiency-label\">Last 7 Days</p>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card task-stats\">\r\n");
      out.write("                    <div class=\"stat-row\">\r\n");
      out.write("                        <span class=\"stat-label\">Total Tasks</span>\r\n");
      out.write("                        <span class=\"stat-value\">");
      out.print( efficiency.getTotalTasks() );
      out.write("</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"stat-row\">\r\n");
      out.write("                        <span class=\"stat-label\">Completed</span>\r\n");
      out.write("                        <span class=\"stat-value success\">");
      out.print( efficiency.getCompletedTasks() );
      out.write("</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"stat-row\">\r\n");
      out.write("                        <span class=\"stat-label\">Pending</span>\r\n");
      out.write("                        <span class=\"stat-value warning\">");
      out.print( efficiency.getPendingTasks() );
      out.write("</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"motivation-banner\">\r\n");
      out.write("                <p class=\"motivation-text\">");
      out.print( efficiency.getMotivationalQuote() );
      out.write("</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"task-controls\">\r\n");
      out.write("                <div class=\"view-tabs\">\r\n");
      out.write("                    <a href=\"task-zone?view=today\" class=\"tab ");
      out.print( currentView.equals("today") ? "active" : "" );
      out.write("\">Today</a>\r\n");
      out.write("                    <a href=\"task-zone?view=upcoming\" class=\"tab ");
      out.print( currentView.equals("upcoming") ? "active" : "" );
      out.write("\">Upcoming</a>\r\n");
      out.write("                    <a href=\"task-zone?view=completed\" class=\"tab ");
      out.print( currentView.equals("completed") ? "active" : "" );
      out.write("\">Completed</a>\r\n");
      out.write("                    <a href=\"task-zone?view=overdue\" class=\"tab ");
      out.print( currentView.equals("overdue") ? "active" : "" );
      out.write("\">Overdue</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <button class=\"btn btn-primary\" onclick=\"openAddTaskModal()\">+ Add Task</button>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card task-list-card\">\r\n");
      out.write("                <div class=\"card-header\">\r\n");
      out.write("                    <h3 class=\"card-title\">");
      out.print( pageTitle );
      out.write("</h3>\r\n");
      out.write("                    <p class=\"card-subtitle\">");
      out.print( tasks.size() );
      out.write(' ');
      out.print( tasks.size() == 1 ? "task" : "tasks" );
      out.write("</p>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                ");
 if (tasks.isEmpty()) { 
      out.write("\r\n");
      out.write("                    <div class=\"empty-state\" style=\"padding: 48px 16px;\">\r\n");
      out.write("                        <div class=\"empty-state-icon\">TASKS</div>\r\n");
      out.write("                        <p>");
 if (currentView.equals("today")) { 
      out.write("No tasks scheduled for today");
 } else if (currentView.equals("completed")) { 
      out.write("No completed tasks yet");
 } else if (currentView.equals("overdue")) { 
      out.write("No overdue tasks");
 } else { 
      out.write("No upcoming tasks");
 } 
      out.write("</p>\r\n");
      out.write("                        <button class=\"btn btn-primary\" onclick=\"openAddTaskModal()\" style=\"margin-top: 16px;\">Create Your First Task</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("                    <div class=\"task-list\">\r\n");
      out.write("                        ");
 for (Task task : tasks) { 
      out.write("\r\n");
      out.write("                            <div class=\"task-item ");
      out.print( task.isCompleted() ? "completed" : "" );
      out.write(' ');
      out.print( task.isOverdue() && !task.isCompleted() ? "overdue" : "" );
      out.write("\">\r\n");
      out.write("                                <div class=\"task-checkbox-wrapper\">\r\n");
      out.write("                                    <form method=\"post\" action=\"task-zone\" style=\"margin: 0;\">\r\n");
      out.write("                                        <input type=\"hidden\" name=\"taskId\" value=\"");
      out.print( task.getTaskId() );
      out.write("\">\r\n");
      out.write("                                        <input type=\"hidden\" name=\"view\" value=\"");
      out.print( currentView );
      out.write("\">\r\n");
      out.write("                                        <input type=\"hidden\" name=\"action\" value=\"");
      out.print( task.isCompleted() ? "uncomplete" : "complete" );
      out.write("\">\r\n");
      out.write("                                        <button type=\"submit\" class=\"task-checkbox ");
      out.print( task.isCompleted() ? "checked" : "" );
      out.write("\" aria-label=\"Toggle task completion\">\r\n");
      out.write("                                            ");
 if (task.isCompleted()) { 
      out.write("\r\n");
      out.write("                                                <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"3\">\r\n");
      out.write("                                                    <polyline points=\"20 6 9 17 4 12\"></polyline>\r\n");
      out.write("                                                </svg>\r\n");
      out.write("                                            ");
 } 
      out.write("\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                    </form>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                \r\n");
      out.write("                                <div class=\"task-content\">\r\n");
      out.write("                                    <div class=\"task-header-row\">\r\n");
      out.write("                                        <h4 class=\"task-title\">");
      out.print( task.getTitle() );
      out.write("</h4>\r\n");
      out.write("                                        <div class=\"task-actions\">\r\n");
      out.write("                                            <button class=\"task-action-btn edit-task-btn\" \r\n");
      out.write("                                                    data-task-id=\"");
      out.print( task.getTaskId() );
      out.write("\" \r\n");
      out.write("                                                    data-title=\"");
      out.print( task.getTitle().replace("\"", "&quot;") );
      out.write("\" \r\n");
      out.write("                                                    data-description=\"");
      out.print( task.getDescription() != null ? task.getDescription().replace("\"", "&quot;") : "" );
      out.write("\" \r\n");
      out.write("                                                    data-type=\"");
      out.print( task.getTaskType() );
      out.write("\" \r\n");
      out.write("                                                    data-category=\"");
      out.print( task.getCategoryId() );
      out.write("\" \r\n");
      out.write("                                                    data-date=\"");
      out.print( task.getTaskDate() != null ? dateFormat.format(task.getTaskDate()) : "" );
      out.write("\" \r\n");
      out.write("                                                    data-time=\"");
      out.print( task.getTaskTime() != null ? timeFormat.format(task.getTaskTime()) : "" );
      out.write("\">Edit</button>\r\n");
      out.write("                                            <form method=\"post\" action=\"task-zone\" style=\"display: inline; margin: 0;\">\r\n");
      out.write("                                                <input type=\"hidden\" name=\"taskId\" value=\"");
      out.print( task.getTaskId() );
      out.write("\">\r\n");
      out.write("                                                <input type=\"hidden\" name=\"view\" value=\"");
      out.print( currentView );
      out.write("\">\r\n");
      out.write("                                                <input type=\"hidden\" name=\"action\" value=\"delete\">\r\n");
      out.write("                                                <button type=\"submit\" class=\"task-action-btn delete\" onclick=\"return confirm('Delete this task?')\">Delete</button>\r\n");
      out.write("                                            </form>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    \r\n");
      out.write("                                    ");
 if (task.getDescription() != null && !task.getDescription().isEmpty()) { 
      out.write("\r\n");
      out.write("                                        <p class=\"task-description\">");
      out.print( task.getDescription() );
      out.write("</p>\r\n");
      out.write("                                    ");
 } 
      out.write("\r\n");
      out.write("                                    \r\n");
      out.write("                                    <div class=\"task-meta\">\r\n");
      out.write("                                        <span class=\"task-badge ");
      out.print( task.getTaskType().toLowerCase() );
      out.write('"');
      out.write('>');
      out.print( task.getTaskType() );
      out.write("</span>\r\n");
      out.write("                                        <span class=\"task-badge category\">");
      out.print( task.getCategoryName() );
      out.write("</span>\r\n");
      out.write("                                        ");
 if (task.getTaskDate() != null) { 
      out.write("\r\n");
      out.write("                                            <span class=\"task-date\">\r\n");
      out.write("                                                <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" style=\"width: 14px; height: 14px; margin-right: 4px;\">\r\n");
      out.write("                                                    <rect x=\"3\" y=\"4\" width=\"18\" height=\"18\" rx=\"2\" ry=\"2\"></rect>\r\n");
      out.write("                                                    <line x1=\"16\" y1=\"2\" x2=\"16\" y2=\"6\"></line>\r\n");
      out.write("                                                    <line x1=\"8\" y1=\"2\" x2=\"8\" y2=\"6\"></line>\r\n");
      out.write("                                                    <line x1=\"3\" y1=\"10\" x2=\"21\" y2=\"10\"></line>\r\n");
      out.write("                                                </svg>\r\n");
      out.write("                                                ");
      out.print( displayDateFormat.format(task.getTaskDate()) );
      out.write("\r\n");
      out.write("                                            </span>\r\n");
      out.write("                                        ");
 } 
      out.write("\r\n");
      out.write("                                        ");
 if (task.getTaskTime() != null) { 
      out.write("\r\n");
      out.write("                                            <span class=\"task-time\">\r\n");
      out.write("                                                <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" style=\"width: 14px; height: 14px; margin-right: 4px;\">\r\n");
      out.write("                                                    <circle cx=\"12\" cy=\"12\" r=\"10\"></circle>\r\n");
      out.write("                                                    <polyline points=\"12 6 12 12 16 14\"></polyline>\r\n");
      out.write("                                                </svg>\r\n");
      out.write("                                                ");
      out.print( timeFormat.format(task.getTaskTime()) );
      out.write("\r\n");
      out.write("                                            </span>\r\n");
      out.write("                                        ");
 } 
      out.write("\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </main>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"addTaskModal\" class=\"modal\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <h3>Add New Task</h3>\r\n");
      out.write("                <button class=\"modal-close\" onclick=\"closeAddTaskModal()\">&times;</button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <form method=\"post\" action=\"task-zone\">\r\n");
      out.write("                <input type=\"hidden\" name=\"action\" value=\"add\">\r\n");
      out.write("                <input type=\"hidden\" name=\"view\" value=\"");
      out.print( currentView );
      out.write("\">\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label class=\"form-label\" for=\"title\">Task Title</label>\r\n");
      out.write("                    <input type=\"text\" id=\"title\" name=\"title\" class=\"form-input\" required placeholder=\"Enter task title\">\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label class=\"form-label\" for=\"description\">Description (Optional)</label>\r\n");
      out.write("                    <textarea id=\"description\" name=\"description\" class=\"form-input\" rows=\"3\" placeholder=\"Add task details\"></textarea>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label class=\"form-label\" for=\"taskType\">Task Type</label>\r\n");
      out.write("                    <select id=\"taskType\" name=\"taskType\" class=\"form-input\" required onchange=\"toggleDateTimeFields()\">\r\n");
      out.write("                        <option value=\"SPECIAL\">Special Task</option>\r\n");
      out.write("                        <option value=\"ROUTINE\">Daily Routine</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label class=\"form-label\" for=\"categoryId\">Category</label>\r\n");
      out.write("                    <select id=\"categoryId\" name=\"categoryId\" class=\"form-input\" required>\r\n");
      out.write("                        ");
 for (Category cat : categories) { 
      out.write("\r\n");
      out.write("                            <option value=\"");
      out.print( cat.getCategoryId() );
      out.write('"');
      out.write('>');
      out.print( cat.getCategoryName() );
      out.write("</option>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div id=\"dateTimeFields\">\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label class=\"form-label\" for=\"taskDate\">Date</label>\r\n");
      out.write("                        <input type=\"date\" id=\"taskDate\" name=\"taskDate\" class=\"form-input\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label class=\"form-label\" for=\"taskTime\">Time (Optional)</label>\r\n");
      out.write("                        <input type=\"time\" id=\"taskTime\" name=\"taskTime\" class=\"form-input\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <button type=\"submit\" class=\"btn btn-primary\" style=\"width: 100%; margin-top: 8px;\">Create Task</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"editTaskModal\" class=\"modal\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <h3>Edit Task</h3>\r\n");
      out.write("                <button class=\"modal-close\" onclick=\"closeEditTaskModal()\">&times;</button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <form method=\"post\" action=\"task-zone\">\r\n");
      out.write("                <input type=\"hidden\" name=\"action\" value=\"edit\">\r\n");
      out.write("                <input type=\"hidden\" name=\"view\" value=\"");
      out.print( currentView );
      out.write("\">\r\n");
      out.write("                <input type=\"hidden\" id=\"editTaskId\" name=\"taskId\">\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label class=\"form-label\" for=\"editTitle\">Task Title</label>\r\n");
      out.write("                    <input type=\"text\" id=\"editTitle\" name=\"title\" class=\"form-input\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label class=\"form-label\" for=\"editDescription\">Description</label>\r\n");
      out.write("                    <textarea id=\"editDescription\" name=\"description\" class=\"form-input\" rows=\"3\"></textarea>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label class=\"form-label\" for=\"editTaskType\">Task Type</label>\r\n");
      out.write("                    <select id=\"editTaskType\" name=\"taskType\" class=\"form-input\" required onchange=\"toggleEditDateTimeFields()\">\r\n");
      out.write("                        <option value=\"SPECIAL\">Special Task</option>\r\n");
      out.write("                        <option value=\"ROUTINE\">Daily Routine</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label class=\"form-label\" for=\"editCategoryId\">Category</label>\r\n");
      out.write("                    <select id=\"editCategoryId\" name=\"categoryId\" class=\"form-input\" required>\r\n");
      out.write("                        ");
 for (Category cat : categories) { 
      out.write("\r\n");
      out.write("                            <option value=\"");
      out.print( cat.getCategoryId() );
      out.write('"');
      out.write('>');
      out.print( cat.getCategoryName() );
      out.write("</option>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div id=\"editDateTimeFields\">\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label class=\"form-label\" for=\"editTaskDate\">Date</label>\r\n");
      out.write("                        <input type=\"date\" id=\"editTaskDate\" name=\"taskDate\" class=\"form-input\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label class=\"form-label\" for=\"editTaskTime\">Time</label>\r\n");
      out.write("                        <input type=\"time\" id=\"editTaskTime\" name=\"taskTime\" class=\"form-input\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <button type=\"submit\" class=\"btn btn-primary\" style=\"width: 100%; margin-top: 8px;\">Update Task</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"js/theme.js\"></script>\r\n");
      out.write("    <script src=\"js/task-zone.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
